export const insectTaxonomyData = [
  {
    id: 'archaeognatha',
    group: 'ancient',
    order_cn: '缨尾目',
    order_en: 'Jumping Bristletails',
    order_latin: 'Archaeognatha',
    focus_cn: '跳跃石蛃类群',
    focus_en: 'Primitive bristletails',
    focus_latin: 'Machilidae',
    summary: '原始无翅昆虫，身体细长、覆鳞片，善于快速弹跳，多见于岩面、树皮和潮湿缝隙。',
    focus_image: '/insect-taxonomy/jumping-bristletail.jpg',
    species: [
      {
        name_cn: '海滨石蛃',
        name_en: 'Marine Bristletail',
        latin: 'Petrobius maritimus',
        image: '/insect-taxonomy/petrobius-maritimus.jpg',
        url: 'https://en.wikipedia.org/wiki/Petrobius_maritimus',
      },
    ],
  },
  {
    id: 'zygentoma',
    group: 'ancient',
    order_cn: '衣鱼目',
    order_en: 'Silverfish',
    order_latin: 'Zygentoma',
    focus_cn: '衣鱼类群',
    focus_en: 'Silverfish and firebrats',
    focus_latin: 'Lepismatidae',
    summary: '体表有银灰色鳞片，喜阴暗潮湿环境，是典型的无翅家居昆虫类群。',
    focus_image: '/insect-taxonomy/silverfish.jpg',
    species: [
      {
        name_cn: '衣鱼',
        name_en: 'Silverfish',
        latin: 'Lepisma saccharinum',
        image: '/insect-taxonomy/lepisma-saccharinum.jpg',
        url: 'https://en.wikipedia.org/wiki/Lepisma_saccharinum',
      },
      {
        name_cn: '火衣鱼',
        name_en: 'Firebrat',
        latin: 'Thermobia domestica',
        image: '/insect-taxonomy/thermobia-domestica.jpg',
        url: 'https://en.wikipedia.org/wiki/Thermobia_domestica',
      },
    ],
  },
  {
    id: 'ephemeroptera',
    group: 'hemi',
    order_cn: '蜉蝣目',
    order_en: 'Mayflies',
    order_latin: 'Ephemeroptera',
    focus_cn: '蜉蝣类群',
    focus_en: 'Mayfly lineage',
    focus_latin: 'Ephemeridae',
    summary: '成虫寿命短、前翅大后翅小，幼虫多水生，是淡水生态监测中的重要指示类群。',
    focus_image: '/insect-taxonomy/mayfly.jpg',
    species: [
      {
        name_cn: '丹麦蜉蝣',
        name_en: 'Green Drake',
        latin: 'Ephemera danica',
        image: '/insect-taxonomy/ephemera-danica.jpg',
        url: 'https://en.wikipedia.org/wiki/Ephemera_danica',
      },
      {
        name_cn: '巨蜉蝣',
        name_en: 'Hexagenia',
        latin: 'Hexagenia limbata',
        image: '/insect-taxonomy/hexagenia-limbata.jpg',
        url: 'https://en.wikipedia.org/wiki/Hexagenia_limbata',
      },
    ],
  },
  {
    id: 'odonata',
    group: 'hemi',
    order_cn: '蜻蜓目',
    order_en: 'Dragonflies and Damselflies',
    order_latin: 'Odonata',
    focus_cn: '蜻蜓与豆娘类群',
    focus_en: 'Aerial predatory insects',
    focus_latin: 'Odonata',
    summary: '复眼发达、翅脉清晰，是典型的空中捕食昆虫，成虫和若虫都具有较强的捕食能力。',
    focus_image: '/insect-taxonomy/dragonfly.jpg',
    species: [
      {
        name_cn: '皇蜻',
        name_en: 'Emperor Dragonfly',
        latin: 'Anax imperator',
        image: '/insect-taxonomy/anax-imperator.jpg',
        url: 'https://en.wikipedia.org/wiki/Anax_imperator',
      },
      {
        name_cn: '丽豆娘',
        name_en: 'Banded Demoiselle',
        latin: 'Calopteryx splendens',
        image: '/insect-taxonomy/calopteryx-splendens.jpg',
        url: 'https://en.wikipedia.org/wiki/Calopteryx_splendens',
      },
    ],
  },
  {
    id: 'plecoptera',
    group: 'hemi',
    order_cn: '襀翅目',
    order_en: 'Stoneflies',
    order_latin: 'Plecoptera',
    focus_cn: '石蝇类群',
    focus_en: 'Stonefly lineage',
    focus_latin: 'Plecoptera',
    summary: '若虫水生，对水质敏感，常被用于溪流生态健康评估。',
    focus_image: '/insect-taxonomy/stonefly.jpg',
    species: [
      {
        name_cn: '大鲑石蝇',
        name_en: 'Giant Salmonfly',
        latin: 'Pteronarcys californica',
        image: '/insect-taxonomy/pteronarcys-californica.jpg',
        url: 'https://en.wikipedia.org/wiki/Pteronarcys_californica',
      },
    ],
  },
  {
    id: 'blattodea',
    group: 'hemi',
    order_cn: '蜚蠊目',
    order_en: 'Cockroaches and Termites',
    order_latin: 'Blattodea',
    focus_cn: '蜚蠊与白蚁类群',
    focus_en: 'Cockroach-termites lineage',
    focus_latin: 'Blattodea',
    summary: '现代分类中白蚁被并入蜚蠊目，这一类群涵盖杂食型蜚蠊与高度社会性的白蚁。',
    focus_image: '/insect-taxonomy/cockroach.png',
    species: [
      {
        name_cn: '美洲大蠊',
        name_en: 'American Cockroach',
        latin: 'Periplaneta americana',
        image: '/insect-taxonomy/periplaneta-americana.jpg',
        url: 'https://en.wikipedia.org/wiki/Periplaneta_americana',
      },
      {
        name_cn: '非洲大白蚁',
        name_en: 'African Termite',
        latin: 'Macrotermes bellicosus',
        image: '/insect-taxonomy/macrotermes-bellicosus.jpg',
        url: 'https://en.wikipedia.org/wiki/Macrotermes_bellicosus',
      },
    ],
  },
  {
    id: 'mantodea',
    group: 'hemi',
    order_cn: '螳螂目',
    order_en: 'Mantises',
    order_latin: 'Mantodea',
    focus_cn: '螳螂类群',
    focus_en: 'Predatory mantises',
    focus_latin: 'Mantodea',
    summary: '前足特化为捕捉足，头部活动灵活，是伪装与伏击捕食结合得非常典型的一支。',
    focus_image: '/insect-taxonomy/mantis.jpg',
    species: [
      {
        name_cn: '欧洲螳螂',
        name_en: 'European Mantis',
        latin: 'Mantis religiosa',
        image: '/insect-taxonomy/mantis-religiosa.jpg',
        url: 'https://en.wikipedia.org/wiki/Mantis_religiosa',
      },
      {
        name_cn: '兰花螳螂',
        name_en: 'Orchid Mantis',
        latin: 'Hymenopus coronatus',
        image: '/insect-taxonomy/hymenopus-coronatus.jpg',
        url: 'https://en.wikipedia.org/wiki/Hymenopus_coronatus',
      },
    ],
  },
  {
    id: 'dermaptera',
    group: 'hemi',
    order_cn: '革翅目',
    order_en: 'Earwigs',
    order_latin: 'Dermaptera',
    focus_cn: '蠼螋类群',
    focus_en: 'Earwig lineage',
    focus_latin: 'Forficulidae',
    summary: '尾端具有显著尾钳，昼伏夜出，常活动于腐殖质、石块和落叶层中。',
    focus_image: '/insect-taxonomy/earwig.jpg',
    species: [
      {
        name_cn: '普通蠼螋',
        name_en: 'European Earwig',
        latin: 'Forficula auricularia',
        image: '/insect-taxonomy/forficula-auricularia.jpg',
        url: 'https://en.wikipedia.org/wiki/Forficula_auricularia',
      },
      {
        name_cn: '海岸蠼螋',
        name_en: 'Maritime Earwig',
        latin: 'Anisolabis maritima',
        image: '/insect-taxonomy/anisolabis-maritima.png',
        url: 'https://en.wikipedia.org/wiki/Anisolabis_maritima',
      },
    ],
  },
  {
    id: 'orthoptera',
    group: 'hemi',
    order_cn: '直翅目',
    order_en: 'Grasshoppers and Crickets',
    order_latin: 'Orthoptera',
    focus_cn: '蝗虫与蟋蟀类群',
    focus_en: 'Jumping and stridulating insects',
    focus_latin: 'Orthoptera',
    summary: '后足适于跳跃，许多类群能通过摩擦发声，是田野环境中最常见的昆虫目之一。',
    focus_image: '/insect-taxonomy/orthoptera.jpg',
    species: [
      {
        name_cn: '飞蝗',
        name_en: 'Migratory Locust',
        latin: 'Locusta migratoria',
        image: '/insect-taxonomy/locusta-migratoria.jpg',
        url: 'https://en.wikipedia.org/wiki/Locusta_migratoria',
      },
      {
        name_cn: '田野蟋蟀',
        name_en: 'Field Cricket',
        latin: 'Gryllus campestris',
        image: '/insect-taxonomy/gryllus-campestris.jpg',
        url: 'https://en.wikipedia.org/wiki/Gryllus_campestris',
      },
    ],
  },
  {
    id: 'phasmatodea',
    group: 'hemi',
    order_cn: '竹节虫目',
    order_en: 'Stick and Leaf Insects',
    order_latin: 'Phasmatodea',
    focus_cn: '竹节虫与叶䗛类群',
    focus_en: 'Masters of twig and leaf mimicry',
    focus_latin: 'Phasmatodea',
    summary: '体型和姿态高度拟态树枝或叶片，是复杂背景识别里最具代表性的伪装昆虫之一。',
    focus_image: '/insect-taxonomy/stick-insect.jpg',
    species: [
      {
        name_cn: '印度竹节虫',
        name_en: 'Indian Stick Insect',
        latin: 'Carausius morosus',
        image: '/insect-taxonomy/carausius-morosus.jpg',
        url: 'https://en.wikipedia.org/wiki/Carausius_morosus',
      },
      {
        name_cn: '菲律宾叶䗛',
        name_en: 'Philippine Leaf Insect',
        latin: 'Phyllium philippinicum',
        image: '/insect-taxonomy/phyllium-philippinicum.jpg',
        url: 'https://en.wikipedia.org/wiki/Phyllium_philippinicum',
      },
    ],
  },
  {
    id: 'hemiptera',
    group: 'hemi',
    order_cn: '半翅目',
    order_en: 'True Bugs, Cicadas and Allies',
    order_latin: 'Hemiptera',
    focus_cn: '蝽类与蝉类群',
    focus_en: 'Piercing-sucking insects',
    focus_latin: 'Hemiptera',
    summary: '口器特化为刺吸式，既包括蝉、叶蝉，也包括椿象、蚜虫等多类农林相关昆虫。',
    focus_image: '/insect-taxonomy/hemiptera.jpg',
    species: [
      {
        name_cn: '南方绿蝽',
        name_en: 'Southern Green Stink Bug',
        latin: 'Nezara viridula',
        image: '/insect-taxonomy/nezara-viridula.jpg',
        url: 'https://en.wikipedia.org/wiki/Nezara_viridula',
      },
      {
        name_cn: '周期蝉',
        name_en: 'Periodical Cicada',
        latin: 'Magicicada septendecim',
        image: '/insect-taxonomy/magicicada-septendecim.jpg',
        url: 'https://en.wikipedia.org/wiki/Magicicada_septendecim',
      },
    ],
  },
  {
    id: 'thysanoptera',
    group: 'hemi',
    order_cn: '缨翅目',
    order_en: 'Thrips',
    order_latin: 'Thysanoptera',
    focus_cn: '蓟马类群',
    focus_en: 'Thrips lineage',
    focus_latin: 'Thripidae',
    summary: '个体微小、翅缘具缨毛，很多种类与花、嫩叶和作物病害传播密切相关。',
    focus_image: '/insect-taxonomy/thrips.jpg',
    species: [
      {
        name_cn: '西花蓟马',
        name_en: 'Western Flower Thrips',
        latin: 'Frankliniella occidentalis',
        image: '/insect-taxonomy/frankliniella-occidentalis.jpg',
        url: 'https://en.wikipedia.org/wiki/Frankliniella_occidentalis',
      },
      {
        name_cn: '葱蓟马',
        name_en: 'Onion Thrips',
        latin: 'Thrips tabaci',
        image: '/insect-taxonomy/thrips-tabaci.jpg',
        url: 'https://en.wikipedia.org/wiki/Thrips_tabaci',
      },
    ],
  },
  {
    id: 'psocodea',
    group: 'hemi',
    order_cn: '啮虫目',
    order_en: 'Booklice and Lice',
    order_latin: 'Psocodea',
    focus_cn: '书虱与虱类群',
    focus_en: 'Booklice-louse lineage',
    focus_latin: 'Psocodea',
    summary: '包括自由生活的书虱与寄生性的虱类，是现代昆虫系统中差异很大的一个大类群。',
    focus_image: '/insect-taxonomy/booklouse.jpg',
    species: [
      {
        name_cn: '谷盗书虱',
        name_en: 'Booklouse',
        latin: 'Liposcelis bostrychophila',
        image: '/insect-taxonomy/liposcelis-bostrychophila.jpg',
        url: 'https://en.wikipedia.org/wiki/Liposcelis_bostrychophila',
      },
      {
        name_cn: '头虱',
        name_en: 'Head Louse',
        latin: 'Pediculus humanus capitis',
        image: '/insect-taxonomy/pediculus-humanus-capitis.jpg',
        url: 'https://en.wikipedia.org/wiki/Pediculus_humanus_capitis',
      },
    ],
  },
  {
    id: 'neuroptera',
    group: 'holo',
    order_cn: '脉翅目',
    order_en: 'Lacewings and Antlions',
    order_latin: 'Neuroptera',
    focus_cn: '草蛉与蚁蛉类群',
    focus_en: 'Net-veined insects',
    focus_latin: 'Neuroptera',
    summary: '翅脉细密发达，幼虫多为积极捕食者，在生物防治和自然控制中很有价值。',
    focus_image: '/insect-taxonomy/lacewing.jpg',
    species: [
      {
        name_cn: '绿草蛉',
        name_en: 'Common Green Lacewing',
        latin: 'Chrysoperla carnea',
        image: '/insect-taxonomy/chrysoperla-carnea.jpg',
        url: 'https://en.wikipedia.org/wiki/Chrysoperla_carnea',
      },
      {
        name_cn: '蚁蛉',
        name_en: 'Antlion',
        latin: 'Myrmeleon formicarius',
        image: '/insect-taxonomy/myrmeleon-formicarius.jpg',
        url: 'https://en.wikipedia.org/wiki/Myrmeleon_formicarius',
      },
    ],
  },
  {
    id: 'coleoptera',
    group: 'holo',
    order_cn: '鞘翅目',
    order_en: 'Beetles',
    order_latin: 'Coleoptera',
    focus_cn: '甲虫类群',
    focus_en: 'The largest insect order',
    focus_latin: 'Coleoptera',
    summary: '前翅特化为鞘翅，是现生昆虫中物种最丰富的一目，生态类型极为多样。',
    focus_image: '/insect-taxonomy/beetle.png',
    species: [
      {
        name_cn: '七星瓢虫',
        name_en: 'Seven-spotted Ladybird',
        latin: 'Coccinella septempunctata',
        image: '/insect-taxonomy/coccinella-septempunctata.jpg',
        url: 'https://en.wikipedia.org/wiki/Coccinella_septempunctata',
      },
      {
        name_cn: '鹿角锹甲',
        name_en: 'Stag Beetle',
        latin: 'Lucanus cervus',
        image: '/insect-taxonomy/lucanus-cervus.jpg',
        url: 'https://en.wikipedia.org/wiki/Lucanus_cervus',
      },
    ],
  },
  {
    id: 'lepidoptera',
    group: 'holo',
    order_cn: '鳞翅目',
    order_en: 'Butterflies and Moths',
    order_latin: 'Lepidoptera',
    focus_cn: '蝶蛾类群',
    focus_en: 'Scaled-wing insects',
    focus_latin: 'Lepidoptera',
    summary: '翅面覆有鳞片，包含大量授粉昆虫和植食性昆虫，是公众最熟悉的昆虫类群之一。',
    focus_image: '/insect-taxonomy/butterfly.jpg',
    species: [
      {
        name_cn: '凤蝶',
        name_en: 'Old World Swallowtail',
        latin: 'Papilio machaon',
        image: '/insect-taxonomy/papilio-machaon.jpg',
        url: 'https://en.wikipedia.org/wiki/Papilio_machaon',
      },
      {
        name_cn: '阿特拉斯天蚕蛾',
        name_en: 'Atlas Moth',
        latin: 'Attacus atlas',
        image: '/insect-taxonomy/attacus-atlas.jpg',
        url: 'https://en.wikipedia.org/wiki/Attacus_atlas',
      },
    ],
  },
  {
    id: 'diptera',
    group: 'holo',
    order_cn: '双翅目',
    order_en: 'Flies and Mosquitoes',
    order_latin: 'Diptera',
    focus_cn: '蝇类与蚊类群',
    focus_en: 'Single-winged flight specialists',
    focus_latin: 'Diptera',
    summary: '后翅退化为平衡棒，飞行机动性强，包括家蝇、蚊、食蚜蝇等多类重要昆虫。',
    focus_image: '/insect-taxonomy/fly.jpg',
    species: [
      {
        name_cn: '家蝇',
        name_en: 'Housefly',
        latin: 'Musca domestica',
        image: '/insect-taxonomy/musca-domestica.jpg',
        url: 'https://en.wikipedia.org/wiki/Musca_domestica',
      },
      {
        name_cn: '埃及伊蚊',
        name_en: 'Yellow Fever Mosquito',
        latin: 'Aedes aegypti',
        image: '/insect-taxonomy/aedes-aegypti.jpg',
        url: 'https://en.wikipedia.org/wiki/Aedes_aegypti',
      },
    ],
  },
  {
    id: 'hymenoptera',
    group: 'holo',
    order_cn: '膜翅目',
    order_en: 'Bees, Wasps and Ants',
    order_latin: 'Hymenoptera',
    focus_cn: '蜂类与蚁类群',
    focus_en: 'Social and parasitoid specialists',
    focus_latin: 'Hymenoptera',
    summary: '既包括授粉蜂类，也包括寄生蜂、蚂蚁等高度社会化或高度专化的昆虫谱系。',
    focus_image: '/insect-taxonomy/bee.jpg',
    species: [
      {
        name_cn: '西方蜜蜂',
        name_en: 'Western Honey Bee',
        latin: 'Apis mellifera',
        image: '/insect-taxonomy/apis-mellifera.jpg',
        url: 'https://en.wikipedia.org/wiki/Apis_mellifera',
      },
      {
        name_cn: '熊蜂',
        name_en: 'Buff-tailed Bumblebee',
        latin: 'Bombus terrestris',
        image: '/insect-taxonomy/bombus-terrestris.jpg',
        url: 'https://en.wikipedia.org/wiki/Bombus_terrestris',
      },
    ],
  },
  {
    id: 'trichoptera',
    group: 'holo',
    order_cn: '毛翅目',
    order_en: 'Caddisflies',
    order_latin: 'Trichoptera',
    focus_cn: '石蛾类群',
    focus_en: 'Caddisfly lineage',
    focus_latin: 'Trichoptera',
    summary: '幼虫常利用沙粒、叶片或细枝做护壳，是淡水生态链里很重要的一类完全变态昆虫。',
    focus_image: '/insect-taxonomy/caddisfly.jpg',
    species: [],
  },
  {
    id: 'siphonaptera',
    group: 'holo',
    order_cn: '蚤目',
    order_en: 'Fleas',
    order_latin: 'Siphonaptera',
    focus_cn: '蚤类群',
    focus_en: 'Wingless jumping ectoparasites',
    focus_latin: 'Pulicidae',
    summary: '无翅、侧扁、善跳，多为外寄生昆虫，在宿主动物传播与卫生学上非常重要。',
    focus_image: '/insect-taxonomy/flea.jpg',
    species: [
      {
        name_cn: '猫蚤',
        name_en: 'Cat Flea',
        latin: 'Ctenocephalides felis',
        image: '/insect-taxonomy/ctenocephalides-felis.jpg',
        url: 'https://en.wikipedia.org/wiki/Ctenocephalides_felis',
      },
      {
        name_cn: '人蚤',
        name_en: 'Human Flea',
        latin: 'Pulex irritans',
        image: '/insect-taxonomy/pulex-irritans.jpg',
        url: 'https://en.wikipedia.org/wiki/Pulex_irritans',
      },
    ],
  },
]

export const taxonomyGroupOptions = [
  { value: 'all', label: '全部' },
  { value: 'ancient', label: '原始无翅类' },
  { value: 'hemi', label: '不完全变态' },
  { value: 'holo', label: '完全变态' },
]
