export const taxonomySpeciesSupplement = {
  machilidae: [
    { name_cn: '短尾石蛃', name_en: 'Short-tailed Bristletail', latin: 'Petrobius brevistylis' },
    { name_cn: '德国石蛃', name_en: 'German Bristletail', latin: 'Machilis germanica' },
    { name_cn: '赫拉贝石蛃', name_en: 'Hrabe Bristletail', latin: 'Machilis hrabei' },
    { name_cn: '跃石蛃', name_en: 'Jumping Bristletail', latin: 'Pedetontus saltator' },
    { name_cn: '爱尔兰石蛃', name_en: 'Irish Bristletail', latin: 'Dilta hibernica' },
  ],
  lepismatidae: [
    { name_cn: '长尾衣鱼', name_en: 'Long-tailed Silverfish', latin: 'Ctenolepisma longicaudata' },
    { name_cn: '四线衣鱼', name_en: 'Four-lined Silverfish', latin: 'Ctenolepisma lineata' },
    { name_cn: '幽灵衣鱼', name_en: 'Ghost Silverfish', latin: 'Ctenolepisma calvum' },
    { name_cn: '塔氏衣鱼', name_en: 'Targioni Silverfish', latin: 'Ctenolepisma targionii' },
    { name_cn: '共居衣鱼', name_en: 'Myrmecophilous Silverfish', latin: 'Neoasterolepisma wasmannii' },
  ],
  ephemeridae: [
    { name_cn: '普通蜉蝣', name_en: 'Common Mayfly', latin: 'Ephemera vulgata' },
    { name_cn: '拟蜉蝣', name_en: 'Eastern Green Drake', latin: 'Ephemera simulans' },
    { name_cn: '双带蜉蝣', name_en: 'Two-striped Burrower Mayfly', latin: 'Hexagenia bilineata' },
    { name_cn: '刚蜉蝣', name_en: 'Rigid Burrower Mayfly', latin: 'Hexagenia rigida' },
    { name_cn: '黑尾蜉蝣', name_en: 'Dark-tailed Mayfly', latin: 'Hexagenia atrocaudata' },
  ],
  'burrowing-mayflies': [
    { name_cn: '双带掘穴蜉蝣', name_en: 'Two-striped Burrowing Mayfly', latin: 'Hexagenia bilineata' },
    { name_cn: '刚掘穴蜉蝣', name_en: 'Rigid Burrowing Mayfly', latin: 'Hexagenia rigida' },
    { name_cn: '黑尾掘穴蜉蝣', name_en: 'Dark-tailed Burrowing Mayfly', latin: 'Hexagenia atrocaudata' },
    { name_cn: '普通掘穴蜉蝣', name_en: 'Burrowing Mayfly', latin: 'Hexagenia atrocaudata' },
    { name_cn: '溪岸掘穴蜉蝣', name_en: 'Riverbank Burrowing Mayfly', latin: 'Hexagenia recurvata' },
  ],
  aeshnidae: [
    { name_cn: '蓝绿蜓', name_en: 'Southern Hawker', latin: 'Aeshna cyanea' },
    { name_cn: '棕蜓', name_en: 'Brown Hawker', latin: 'Aeshna grandis' },
    { name_cn: '绿达纳蜓', name_en: 'Common Green Darner', latin: 'Anax junius' },
    { name_cn: '迁飞蜓', name_en: 'Vagrant Emperor', latin: 'Hemianax ephippiger' },
    { name_cn: '秋蜓', name_en: 'Migrant Hawker', latin: 'Aeshna mixta' },
  ],
  calopterygidae: [
    { name_cn: '蓝丽豆娘', name_en: 'Beautiful Demoiselle', latin: 'Calopteryx virgo' },
    { name_cn: '美洲丽豆娘', name_en: 'Ebony Jewelwing', latin: 'Calopteryx maculata' },
    { name_cn: '赤翅豆娘', name_en: 'American Rubyspot', latin: 'Hetaerina americana' },
    { name_cn: '日本豆娘', name_en: 'Japanese Demoiselle', latin: 'Mnais costalis' },
    { name_cn: '蓝带豆娘', name_en: 'Red-winged Demoiselle', latin: 'Neurobasis chinensis' },
  ],
  pteronarcyidae: [
    { name_cn: '东方巨石蝇', name_en: 'Common Salmonfly', latin: 'Pteronarcys dorsata' },
    { name_cn: '褐巨石蝇', name_en: 'Brown Stonefly', latin: 'Pteronarcella badia' },
    { name_cn: '王巨石蝇', name_en: 'Prince Salmonfly', latin: 'Pteronarcys princeps' },
    { name_cn: '康氏巨石蝇', name_en: 'Comstock Salmonfly', latin: 'Pteronarcys comstocki' },
    { name_cn: '普氏巨石蝇', name_en: 'Proteus Salmonfly', latin: 'Pteronarcys proteus' },
  ],
  blattidae: [
    { name_cn: '东方蜚蠊', name_en: 'Oriental Cockroach', latin: 'Blatta orientalis' },
    { name_cn: '德国小蠊', name_en: 'German Cockroach', latin: 'Blattella germanica' },
    { name_cn: '澳洲大蠊', name_en: 'Australian Cockroach', latin: 'Periplaneta australasiae' },
    { name_cn: '烟褐蜚蠊', name_en: 'Smokybrown Cockroach', latin: 'Periplaneta fuliginosa' },
    { name_cn: '褐带蜚蠊', name_en: 'Brown-banded Cockroach', latin: 'Supella longipalpa' },
  ],
  termitidae: [
    { name_cn: '角白蚁', name_en: 'Conehead Termite', latin: 'Nasutitermes corniger' },
    { name_cn: '台湾乳白蚁', name_en: 'Formosan Subterranean Termite', latin: 'Coptotermes formosanus' },
    { name_cn: '黄翅大白蚁', name_en: 'Fungus-growing Termite', latin: 'Odontotermes formosanus' },
    { name_cn: '澳洲田白蚁', name_en: 'Magnetic Termite', latin: 'Amitermes meridionalis' },
    { name_cn: '东部地下白蚁', name_en: 'Eastern Subterranean Termite', latin: 'Reticulitermes flavipes' },
  ],
  mantidae: [
    { name_cn: '中华大刀螳', name_en: 'Chinese Mantis', latin: 'Tenodera sinensis' },
    { name_cn: '广斧螳', name_en: 'Giant Asian Mantis', latin: 'Hierodula patellifera' },
    { name_cn: '非洲大螳', name_en: 'African Mantis', latin: 'Sphodromantis lineola' },
    { name_cn: '地中海螳螂', name_en: 'Mediterranean Mantis', latin: 'Iris oratoria' },
    { name_cn: '卡罗来纳螳螂', name_en: 'Carolina Mantis', latin: 'Stagmomantis carolina' },
  ],
  hymenopodidae: [
    { name_cn: '宝石花螳', name_en: 'Jeweled Flower Mantis', latin: 'Creobroter gemmatus' },
    { name_cn: '彩翅花螳', name_en: 'Painted Flower Mantis', latin: 'Creobroter pictipennis' },
    { name_cn: '优雅花螳', name_en: 'Banded Flower Mantis', latin: 'Theopropus elegans' },
    { name_cn: '布氏花螳', name_en: 'Brunner Mantis', latin: 'Hestiasula brunneriana' },
    { name_cn: '红衣花螳', name_en: 'Cardinal Mantis', latin: 'Helvia cardinalis' },
  ],
  forficulidae: [
    { name_cn: '莱氏蠼螋', name_en: 'Lesne Earwig', latin: 'Forficula lesnei' },
    { name_cn: '迷惑蠼螋', name_en: 'Deceptive Earwig', latin: 'Forficula decipiens' },
    { name_cn: '中间蠼螋', name_en: 'Lesser Earwig', latin: 'Apterygida media' },
    { name_cn: '条斑蠼螋', name_en: 'Striped Earwig', latin: 'Doru luteipes' },
    { name_cn: '海岛蠼螋', name_en: 'Island Earwig', latin: 'Guanchia pubescens' },
  ],
  anisolabididae: [
    { name_cn: '环纹扁尾蠼螋', name_en: 'Ring-legged Earwig', latin: 'Euborellia annulipes' },
    { name_cn: '暗扁尾蠼螋', name_en: 'Dark Earwig', latin: 'Euborellia moesta' },
    { name_cn: '海滨扁尾蠼螋', name_en: 'Littoral Earwig', latin: 'Anisolabis littorea' },
    { name_cn: '红海扁尾蠼螋', name_en: 'Phoenician Earwig', latin: 'Anisolabis phoenicia' },
    { name_cn: '爪尾扁尾蠼螋', name_en: 'Javan Earwig', latin: 'Gonolabis javana' },
  ],
  acrididae: [
    { name_cn: '沙漠蝗', name_en: 'Desert Locust', latin: 'Schistocerca gregaria' },
    { name_cn: '差斑蝗', name_en: 'Differential Grasshopper', latin: 'Melanoplus differentialis' },
    { name_cn: '澳洲瘟蝗', name_en: 'Australian Plague Locust', latin: 'Chortoicetes terminifera' },
    { name_cn: '卡罗莱纳蝗', name_en: 'Carolina Grasshopper', latin: 'Dissosteira carolina' },
    { name_cn: '巨斑蝗', name_en: 'Giant Grasshopper', latin: 'Valanga irregularis' },
  ],
  gryllidae: [
    { name_cn: '家蟋蟀', name_en: 'House Cricket', latin: 'Acheta domesticus' },
    { name_cn: '双斑蟋蟀', name_en: 'Two-spotted Cricket', latin: 'Gryllus bimaculatus' },
    { name_cn: '喜歌蟋蟀', name_en: 'Black Field Cricket', latin: 'Teleogryllus commodus' },
    { name_cn: '海洋蟋蟀', name_en: 'Oceanic Cricket', latin: 'Teleogryllus oceanicus' },
    { name_cn: '小田蟋蟀', name_en: 'Southern Wood Cricket', latin: 'Modicogryllus frontalis' },
  ],
  'stick-mimics': [
    { name_cn: '王冠竹节虫', name_en: 'Spiny Leaf Insect', latin: 'Extatosoma tiaratum' },
    { name_cn: '阿尔忒弥斯竹节虫', name_en: 'Artemis Stick Insect', latin: 'Ramulus artemis' },
    { name_cn: '顽强竹节虫', name_en: 'Robust Stick Insect', latin: 'Cuniculina impigra' },
    { name_cn: '粗刺竹节虫', name_en: 'Prickly Stick Insect', latin: 'Aretaon asperrimus' },
    { name_cn: '褐纹竹节虫', name_en: 'Vietnamese Stick Insect', latin: 'Medauroidea extradentata' },
  ],
  'leaf-mimics': [
    { name_cn: '巨叶䗛', name_en: 'Giant Leaf Insect', latin: 'Phyllium giganteum' },
    { name_cn: '双眼叶䗛', name_en: 'Two-spotted Leaf Insect', latin: 'Phyllium bioculatum' },
    { name_cn: '韦氏叶䗛', name_en: 'Westwood Leaf Insect', latin: 'Phyllium westwoodii' },
    { name_cn: '枯叶叶䗛', name_en: 'Dry Leaf Insect', latin: 'Phyllium siccifolium' },
    { name_cn: '莱氏叶䗛', name_en: 'Letirant Leaf Insect', latin: 'Phyllium letiranti' },
  ],
  pentatomidae: [
    { name_cn: '褐斑蝽', name_en: 'Brown Marmorated Stink Bug', latin: 'Halyomorpha halys' },
    { name_cn: '赤足蝽', name_en: 'Forest Bug', latin: 'Pentatoma rufipes' },
    { name_cn: '条纹蝽', name_en: 'Striped Shield Bug', latin: 'Graphosoma italicum' },
    { name_cn: '绿盾蝽', name_en: 'Green Shield Bug', latin: 'Palomena prasina' },
    { name_cn: '美洲绿蝽', name_en: 'Green Stink Bug', latin: 'Chinavia hilaris' },
  ],
  cicadidae: [
    { name_cn: '普通蝉', name_en: 'Common Cicada', latin: 'Cicada orni' },
    { name_cn: '林奈蝉', name_en: 'Linne Cicada', latin: 'Neotibicen linnei' },
    { name_cn: '欧洲大蝉', name_en: 'Great Mediterranean Cicada', latin: 'Lyristes plebejus' },
    { name_cn: '黑蚱蝉', name_en: 'Black Cicada', latin: 'Cryptotympana atrata' },
    { name_cn: '犬日蝉', name_en: 'Dog-day Cicada', latin: 'Neotibicen canicularis' },
  ],
  'flower-thrips': [
    { name_cn: '棕榈蓟马', name_en: 'Melon Thrips', latin: 'Thrips palmi' },
    { name_cn: '茶黄蓟马', name_en: 'Chilli Thrips', latin: 'Scirtothrips dorsalis' },
    { name_cn: '中间花蓟马', name_en: 'Garden Thrips', latin: 'Frankliniella intonsa' },
    { name_cn: '肖氏花蓟马', name_en: 'Common Blossom Thrips', latin: 'Frankliniella schultzei' },
    { name_cn: '夏威夷蓟马', name_en: 'Hawaiian Flower Thrips', latin: 'Thrips hawaiiensis' },
  ],
  'onion-thrips': [
    { name_cn: '洋葱蓟马', name_en: 'Onion Blossom Thrips', latin: 'Thrips allii' },
    { name_cn: '澳洲葱蓟马', name_en: 'Plague Thrips', latin: 'Thrips imaginis' },
    { name_cn: '剑兰蓟马', name_en: 'Gladiolus Thrips', latin: 'Thrips simplex' },
    { name_cn: '褐翅蓟马', name_en: 'Dark-winged Thrips', latin: 'Thrips fuscipennis' },
    { name_cn: '黄蓟马', name_en: 'Yellow Thrips', latin: 'Thrips flavus' },
  ],
  booklice: [
    { name_cn: '褐书虱', name_en: 'Brown Booklouse', latin: 'Liposcelis decolor' },
    { name_cn: '嗜虫书虱', name_en: 'Entomophilous Booklouse', latin: 'Liposcelis entomophila' },
    { name_cn: '网纹书虱', name_en: 'Reticulate Booklouse', latin: 'Lepinotus reticulatus' },
    { name_cn: '双斑啮虫', name_en: 'Barked Booklouse', latin: 'Psocus bipunctatus' },
    { name_cn: '家居啮虫', name_en: 'Domestic Barklouse', latin: 'Dorypteryx domestica' },
  ],
  lice: [
    { name_cn: '体虱', name_en: 'Body Louse', latin: 'Pediculus humanus corporis' },
    { name_cn: '阴虱', name_en: 'Crab Louse', latin: 'Pthirus pubis' },
    { name_cn: '猪血虱', name_en: 'Pig Louse', latin: 'Haematopinus suis' },
    { name_cn: '牛吸虱', name_en: 'Long-nosed Cattle Louse', latin: 'Linognathus vituli' },
    { name_cn: '牛咀虱', name_en: 'Cattle Biting Louse', latin: 'Bovicola bovis' },
  ],
  chrysopidae: [
    { name_cn: '珍珠草蛉', name_en: 'Pearl Lacewing', latin: 'Chrysopa perla' },
    { name_cn: '红唇草蛉', name_en: 'Green Lacewing', latin: 'Chrysoperla rufilabris' },
    { name_cn: '基斑草蛉', name_en: 'Common Green Lacewing', latin: 'Mallada basalis' },
    { name_cn: '意草蛉', name_en: 'Italian Lacewing', latin: 'Italochrysa italica' },
    { name_cn: '缘毛草蛉', name_en: 'Sedge Lacewing', latin: 'Chrysotropia ciliata' },
  ],
  myrmeleontidae: [
    { name_cn: '普通蚁蛉', name_en: 'European Antlion', latin: 'Euroleon nostras' },
    { name_cn: '北方蚁蛉', name_en: 'Dune Antlion', latin: 'Myrmeleon bore' },
    { name_cn: '大翼蚁蛉', name_en: 'Owlfly-like Antlion', latin: 'Palpares libelluloides' },
    { name_cn: '彩纹蚁蛉', name_en: 'Pretty Antlion', latin: 'Glenoleon pulchellus' },
    { name_cn: '四纹蚁蛉', name_en: 'Distoleon Antlion', latin: 'Distoleon tetragrammicus' },
  ],
  coccinellidae: [
    { name_cn: '异色瓢虫', name_en: 'Harlequin Ladybird', latin: 'Harmonia axyridis' },
    { name_cn: '二星瓢虫', name_en: 'Two-spot Ladybird', latin: 'Adalia bipunctata' },
    { name_cn: '汇聚瓢虫', name_en: 'Convergent Lady Beetle', latin: 'Hippodamia convergens' },
    { name_cn: '日本瓢虫', name_en: 'Japanese Ladybird', latin: 'Propylea japonica' },
    { name_cn: '红缘瓢虫', name_en: 'Red-spotted Ladybird', latin: 'Chilocorus rubidus' },
  ],
  lucanidae: [
    { name_cn: '长颚锹甲', name_en: 'Giraffe Stag Beetle', latin: 'Prosopocoilus giraffa' },
    { name_cn: '泰坦锹甲', name_en: 'Titan Stag Beetle', latin: 'Dorcus titanus' },
    { name_cn: '金属锹甲', name_en: 'Golden Stag Beetle', latin: 'Cyclommatus metallifer' },
    { name_cn: '天堂锹甲', name_en: 'Rainbow Stag Beetle', latin: 'Lamprima adolphinae' },
    { name_cn: '麋角锹甲', name_en: 'American Stag Beetle', latin: 'Lucanus elaphus' },
  ],
  papilionidae: [
    { name_cn: '黑凤蝶', name_en: 'Black Swallowtail', latin: 'Papilio polyxenes' },
    { name_cn: '柑橘凤蝶', name_en: 'Great Mormon', latin: 'Papilio memnon' },
    { name_cn: '绿纹凤蝶', name_en: 'Tailed Jay', latin: 'Graphium agamemnon' },
    { name_cn: '金凤蝶', name_en: 'Common Birdwing', latin: 'Troides helena' },
    { name_cn: '蓝带凤蝶', name_en: 'Pipevine Swallowtail', latin: 'Battus philenor' },
  ],
  saturniidae: [
    { name_cn: '樗蚕蛾', name_en: 'Ailanthus Silkmoth', latin: 'Samia cynthia' },
    { name_cn: '月蛾', name_en: 'Luna Moth', latin: 'Actias luna' },
    { name_cn: '柞蚕蛾', name_en: 'Chinese Oak Silkmoth', latin: 'Antheraea pernyi' },
    { name_cn: '北美天蚕蛾', name_en: 'Cecropia Moth', latin: 'Hyalophora cecropia' },
    { name_cn: '大孔雀蛾', name_en: 'Giant Peacock Moth', latin: 'Saturnia pyri' },
  ],
  muscidae: [
    { name_cn: '厩蝇', name_en: 'Stable Fly', latin: 'Stomoxys calcitrans' },
    { name_cn: '棚蝇', name_en: 'False Stable Fly', latin: 'Muscina stabulans' },
    { name_cn: '牛角蝇', name_en: 'Horn Fly', latin: 'Haematobia irritans' },
    { name_cn: '牧场蝇', name_en: 'Head Fly', latin: 'Hydrotaea irritans' },
    { name_cn: '小家蝇', name_en: 'Lesser House Fly', latin: 'Fannia canicularis' },
  ],
  culicidae: [
    { name_cn: '冈比亚按蚊', name_en: 'Malaria Mosquito', latin: 'Anopheles gambiae' },
    { name_cn: '库蚊', name_en: 'Common House Mosquito', latin: 'Culex pipiens' },
    { name_cn: '白纹伊蚊', name_en: 'Asian Tiger Mosquito', latin: 'Aedes albopictus' },
    { name_cn: '斯氏按蚊', name_en: 'Urban Malaria Mosquito', latin: 'Anopheles stephensi' },
    { name_cn: '致倦库蚊', name_en: 'Southern House Mosquito', latin: 'Culex quinquefasciatus' },
  ],
  apidae: [
    { name_cn: '东方蜜蜂', name_en: 'Eastern Honey Bee', latin: 'Apis cerana' },
    { name_cn: '大蜜蜂', name_en: 'Giant Honey Bee', latin: 'Apis dorsata' },
    { name_cn: '紫蓝木蜂', name_en: 'Violet Carpenter Bee', latin: 'Xylocopa violacea' },
    { name_cn: '长角蜂', name_en: 'Long-horned Bee', latin: 'Eucera longicornis' },
    { name_cn: '兰花蜂', name_en: 'Green Orchid Bee', latin: 'Euglossa dilemma' },
  ],
  bombini: [
    { name_cn: '石熊蜂', name_en: 'Red-tailed Bumblebee', latin: 'Bombus lapidarius' },
    { name_cn: '牧场熊蜂', name_en: 'Common Carder Bee', latin: 'Bombus pascuorum' },
    { name_cn: '北美熊蜂', name_en: 'Common Eastern Bumblebee', latin: 'Bombus impatiens' },
    { name_cn: '树熊蜂', name_en: 'Tree Bumblebee', latin: 'Bombus hypnorum' },
    { name_cn: '白尾熊蜂', name_en: 'White-tailed Bumblebee', latin: 'Bombus lucorum' },
  ],
  psychomyiidae: [
    { name_cn: '小长角石蛾', name_en: 'Little Caddisfly', latin: 'Psychomyia pusilla' },
    { name_cn: '灰长角石蛾', name_en: 'Dark Caddisfly', latin: 'Lype phaeopa' },
    { name_cn: '近似丝石蛾', name_en: 'Similar Tinodes', latin: 'Tinodes assimilis' },
    { name_cn: '淡色丝石蛾', name_en: 'Pale Tinodes', latin: 'Tinodes pallidulus' },
    { name_cn: '黄长角石蛾', name_en: 'Yellow Caddisfly', latin: 'Psychomyia flavida' },
  ],
  'case-making-caddisflies': [
    { name_cn: '大石蛾', name_en: 'Great Caddisfly', latin: 'Phryganea grandis' },
    { name_cn: '月纹石蛾', name_en: 'Crescent Caddisfly', latin: 'Limnephilus lunatus' },
    { name_cn: '辉石蛾', name_en: 'Radiant Caddisfly', latin: 'Halesus radiatus' },
    { name_cn: '面石蛾', name_en: 'Masked Caddisfly', latin: 'Sericostoma personatum' },
    { name_cn: '彩石蛾', name_en: 'Varied Caddisfly', latin: 'Agrypnia varia' },
  ],
  'cat-fleas': [
    { name_cn: '犬蚤', name_en: 'Dog Flea', latin: 'Ctenocephalides canis' },
    { name_cn: '鸡蚤', name_en: 'Sticktight Flea', latin: 'Echidnophaga gallinacea' },
    { name_cn: '鸡羽蚤', name_en: 'Hen Flea', latin: 'Ceratophyllus gallinae' },
    { name_cn: '鼠疫蚤', name_en: 'Oriental Rat Flea', latin: 'Xenopsylla cheopis' },
    { name_cn: '北方鼠蚤', name_en: 'Northern Rat Flea', latin: 'Nosopsyllus fasciatus' },
  ],
  'human-fleas': [
    { name_cn: '穿皮蚤', name_en: 'Chigoe Flea', latin: 'Tunga penetrans' },
    { name_cn: '拟人蚤', name_en: 'American Human Flea', latin: 'Pulex simulans' },
    { name_cn: '亚洲鼠蚤', name_en: 'Asian Rat Flea', latin: 'Xenopsylla astia' },
    { name_cn: '黑蚤', name_en: 'Cat House Flea', latin: 'Ceratophyllus niger' },
    { name_cn: '小鼠蚤', name_en: 'Mouse Flea', latin: 'Leptopsylla segnis' },
  ],
}
